### ISSUE TITLE
autoloading doesn't work

### ISSUE THREAD

**Issue by aaronjensen** [titaniumbones/ox-slack#2]
I don't know if this is a spacemacs specific thing, but the autoloads do not work properly when ox-slack is installed from melpa. My guess is that the setting of `generated-autoload-file` is problematic. I've not seen a package do that before, but I could be mistaken.

**Comment by titaniumbones** [comment]
I'm sure I'm doing something wrong, as this is my first package :confused: I copied that invocation from other org packages, but I see it's rarely placed in other packages.  I'll remove that line and perhaps you can test it out for me?

**Comment by aaronjensen** [comment]
I’d be happy to

**Comment by aaronjensen** [comment]
@titaniumbones that fixed it! thank you.
